# Generated by Django 3.1.3 on 2020-11-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='year_released',
            field=models.DateField(),
        ),
    ]
